pizzas/urls.py
#defines URL patterns for pizzas

from django.urls import path 
#import path() function which is needed when mapping URLs to views
from . import views
from django.contrib.staticfiles.urls import staticfiles_urlpatterns 
#import views.py module from same directory as the current urls.py module
#variable app_name helps django distinguish this urls.py file from the files of the same name in other apps within the project
#the variable urlpattern in this module is a list of individual pages that can be requested from the pizzas app



app_name = 'pizzas'
urlpatterns = [path ('',views.index, name='index'), 
path ('pizzas',views.pizzas, name='pizzas'),
path ('pizzas/<int:pizza_id>/',views.pizza, name='pizza'),
path ('pizzas/<int:pizza_id>/comment/',views.comment, name='comment'),]


#urlpatterns += staticfiles_urlpatterns()





















#the actual url pattern is a call to the path() function, which takes 3 args: '' string that helps django route the current request. Django receives the requested URL and tries to route the request to a view
#routes reqeust to a view by searching all the URL patterns we've defined to find one that matches the current request, so empty string matches the base URL
#any other url won't match this pattern, and django will return an error page if the URL requested doesnt match any existing url patterns

#the second arg in path specifies which function to call in views.py
#when a requested URL matches the pattern we're defining, django calls the index() function from views.py

#the third argument provides the name index for this url pattern so we can refer to it in other code sections
#whenever we want to provide a link to the home page, we'll use this name instead of writing out a URL

pizzeria/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('pizzas.urls')), 
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

pizzas/models.py
from django.db import models
from django import forms

# Create your models here.
class Pizza(models.Model):
    name = models.CharField(max_length = 200)
    date_added = models.DateTimeField(auto_now_add=True)
    image = models.ImageField(upload_to='images',blank=True)

    def __str__(self):
        return self.name

class Toppings(models.Model):
    pizza = models.ForeignKey(Pizza, on_delete=models.CASCADE)
    name = models.TextField()
    date_added = models.DateTimeField(auto_now_add=True)


    class Meta:
        verbose_name_plural = 'toppings'
        
    def __str__(self):
        #return a string representation of the model
        return f"{self.name[:50]}"
        #tells django which info to show just 50 characters of text, and ... means not displaying entire entry

class Comment(models.Model):
    pizza = models.ForeignKey(Pizza, on_delete=models.CASCADE)
    text = models.CharField(max_length=200)
    date_added = models.DateTimeField(auto_now_add=True)
    

    class Meta:
        verbose_name_plural = "comments"

    def __str__(self):
        return f"{self.text[:50]}..."

pizzas/forms.py
from django import forms 

from .models import Pizza, Comment

'''
class PizzaForm(forms.ModelForm):
    class Meta:
        model = Pizza
        fields = ["name"]
        label = {"Name:": ""}
        widgets = {"name": forms.Textarea(attrs={"cols": 80})}
'''

class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ['text']
        labels = {'text':''}

pizzas/views.py
from django.shortcuts import render, redirect
from .models import Pizza, Toppings
from .forms import CommentForm

def index(request):
    return render(request, 'pizzas/index.html')


def pizzas(request):
    pizzas = Pizza.objects.order_by('date_added')
    context = {'pizzas':pizzas}
    return render(request, 'pizzas/pizzas.html', context)


def pizza(request, pizza_id):
  
    pizza = Pizza.objects.get(id=pizza_id)
    toppings = pizza.toppings_set.order_by('-date_added')
    comments=pizza.comment_set.order_by('-date_added')
    context = {'pizza':pizza, 'toppings':toppings, 'comments':comments}
    return render(request,'pizzas/pizza.html', context)
   
def comment(request, pizza_id):
    if request.method != 'POST':
        form=CommentForm()
    else:
        pizza = Pizza.objects.get(id = pizza_id)
        form=CommentForm(data=request.POST)
        if form.is_valid():
            comment=form.save(commit=False)
            comment.pizza=pizza
            comment.save()
            return redirect('pizzas:pizzas')
    context={'form':form, 'pizza_id': pizza_id}
    return render(request,'pizzas/comment.html',context)

pizzas/templates/pizzas/availpizzas.html
<body style="background-color: rgb(247, 169, 1);"></body>
{% extends "pizzas/base.html" %}
{% block content %}

<p>Pizzas Available</p>
<ul>
    {% for pizza in availpizzas %}
    <li>
        <a href="{% url 'pizzas:pizza' pizza.id %}">{{ pizza }}</a>
    </li>
    {% empty %}
    <li>No pizzas have been added yet.</li>
    {% endfor %}
</ul>

{% endblock content %}

pizzas/templates/pizzas/base.html
<p>
    <a href="{% url 'pizzas:index' %}">Home</a>
    <a href="{% url 'pizzas:pizzas' %}">Available Pizzas</a>
</p>
{% block content %}
{% endblock content%}

pizzas/templates/pizzas/comment.html
{% extends "pizzas/base.html" %}

{% block content %}
<p>Add Comment:</p>

<form action="{% url 'pizzas:comment' pizza_id %}" method='post'>
    {% csrf_token %}
    {{form.as_p}}
    <button name="submit">Add Comment</button>
</form>

{% endblock content %}

pizzas/templates/pizzas/index.html
<body style="background-color: rgb(247, 169, 1);"></body>
{% extends "pizzas/base.html" %}

{% block content %}
<p>Welcome to our Menu!</p>
<p>We would love to serve you!</p>
<p>
    {% load static %} <img src="{% static 'pizzas/media/cover.jpg' %}" class="center" />
</p>
{% endblock content %}

pizzas/templates/pizzas/pizza.html
{% extends "pizzas/base.html" %}
{% block content %}

<body style="background-color:rgb(247, 169, 1)">
    <p>Pizza: {{ pizza }}</p>
    <h2><img src="{{pizza.image.url}}" class="img-thumbnail" style="max-height:250px;" alt=""></h2>
    <div>Toppings</div>
    <ul>
        {% for topping in toppings %}
        <li>

            <p>{{topping.name|linebreaks}}</p>
            <p> {{topping.date_added|date:'M d,Y H:i'}}</p>
        </li>
        {% empty %}
        <li>No toppings for this pizza </li>
        {% endfor %}
    </ul>
    <div>Comments</div>
    <ul>
        {% for comment in comments %}
        <li>
            <p>{{ comment.text }}</p>
            <p>{{comment.date_added|date:'M d,Y H:i'}}</p>
        </li>
        {% empty %}
        <li>No Comments for this pizza </li>
        {% endfor %}
    </ul>
</body>
{% endblock content %}

pizzas/templates/pizzas/pizzas.html
<body style="background-color: rgb(247, 169, 1);"></body>
{% extends "pizzas/base.html" %}
{% block content %}

<p>Pizzas Available</p>
<ul>
    {% for pizza in pizzas %}
    <li>
        <a href="{% url 'pizzas:pizza' pizza.id %}">{{ pizza }}</a>
        <a href="{% url 'pizzas:comment' pizza.id %}">Add a Comment</a>
    </li>
    {% empty %}
    <li>No pizzas have been added yet.</li>
    {% endfor %}
</ul>

{% endblock content %}